"""empty message

Revision ID: 439805498794
Revises: merge_heads_001
Create Date: 2024-10-29 20:04:24.802087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439805498794'
down_revision = 'merge_heads_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nif', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('morada', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nif')
    )
    op.create_table('assistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('imei', sa.String(length=20), nullable=False),
    sa.Column('codigo_seguranca', sa.String(length=50), nullable=False),
    sa.Column('avaria', sa.String(length=200), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('tecnico', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('orçamentado', 'reparado', 'entregue', name='estado_assistencia'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('data_entrada', sa.DateTime(), nullable=False),
    sa.Column('data_saida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assistencia')
    op.drop_table('cliente')
    # ### end Alembic commands ###
