"""update optional fields

Revision ID: ec89c021f994
Revises: 439805498794
Create Date: 2024-11-06 17:19:04.956527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec89c021f994'
down_revision = '439805498794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistencia', 'imei',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('assistencia', 'codigo_seguranca',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('assistencia', 'valor',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('cliente', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cliente', 'nif',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('cliente', 'morada',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'morada',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('cliente', 'nif',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('cliente', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('assistencia', 'valor',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('assistencia', 'codigo_seguranca',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('assistencia', 'imei',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
